In [1]:
pip install rasterio

     |████████████████████████████████| 31.0 MB 30.2 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [2]:
import rasterio
band_red = 1
band_green=2
band_blue=3
band_nir=4  

raster = rasterio.open('m_3009743_sw_14_060_20201018.tif')
red = raster.read(band_red) 
green=raster.read(band_green)
blue=raster.read(band_blue)
nir=raster.read(band_nir)

## Red Band Average

In [3]:
red.shape

(12320, 10820)

In [4]:
import numpy as np

avg = np.zeros((red.shape[0]-2, red.shape[1]-2))

#slide a 3x3 window over the red bands
for i in range(red.shape[0]-2):
  for j in range(red.shape[1]-2):
    number= np.average([red[i][j],red[i][j+1],red[i][j+2],
                        red[i+1][j],red[i+1][j+1],red[i+1][j+2],
                        red[i+2][j],red[i+2][j+1],red[i+2][j+2]])
    avg[i][j]=number

#avg

In [5]:
avg.shape

(12318, 10818)

In [6]:
print(avg)

[[54.44444444 56.22222222 57.         ... 60.88888889 61.33333333
  61.33333333]
 [53.11111111 53.77777778 54.66666667 ... 61.44444444 60.77777778
  60.22222222]
 [53.11111111 53.         53.33333333 ... 59.33333333 58.11111111
  57.55555556]
 ...
 [41.44444444 41.44444444 39.44444444 ... 73.55555556 67.11111111
  67.66666667]
 [40.11111111 39.55555556 37.77777778 ... 75.77777778 68.33333333
  66.77777778]
 [44.11111111 41.33333333 39.55555556 ... 77.         70.88888889
  69.11111111]]


## Green Band Average

In [8]:
avg_green = np.zeros((green.shape[0]-2, green.shape[1]-2))

#slide a 3x3 window over the green bands
for i in range(green.shape[0]-2):
  for j in range(green.shape[1]-2):
    number_green= np.average([green[i][j],green[i][j+1],green[i][j+2],
                        green[i+1][j],green[i+1][j+1],green[i+1][j+2],
                        green[i+2][j],green[i+2][j+1],green[i+2][j+2]])
    avg_green[i][j]=number_green

In [9]:
print(avg_green)

[[56.77777778 58.22222222 59.44444444 ... 70.33333333 70.44444444
  70.66666667]
 [56.         56.33333333 57.22222222 ... 71.         70.44444444
  70.11111111]
 [56.77777778 56.33333333 56.11111111 ... 68.22222222 67.66666667
  67.44444444]
 ...
 [48.66666667 47.44444444 44.55555556 ... 86.11111111 75.55555556
  73.33333333]
 [47.33333333 45.44444444 42.66666667 ... 87.55555556 76.55555556
  72.44444444]
 [51.44444444 47.44444444 43.77777778 ... 86.44444444 78.33333333
  75.55555556]]


## Blue Band Average

In [10]:
avg_blue = np.zeros((blue.shape[0]-2, blue.shape[1]-2))

#slide a 3x3 window over the blue bands
for i in range(blue.shape[0]-2):
  for j in range(blue.shape[1]-2):
    number_blue= np.average([blue[i][j],blue[i][j+1],blue[i][j+2],
                        blue[i+1][j],blue[i+1][j+1],blue[i+1][j+2],
                        blue[i+2][j],blue[i+2][j+1],blue[i+2][j+2]])
    avg_blue[i][j]=number_blue

In [11]:
print(avg_blue)

[[71.22222222 72.33333333 73.44444444 ... 67.22222222 67.22222222
  67.22222222]
 [70.33333333 70.33333333 70.88888889 ... 67.33333333 66.88888889
  66.66666667]
 [71.22222222 70.44444444 70.11111111 ... 66.44444444 66.
  65.88888889]
 ...
 [65.44444444 64.66666667 63.44444444 ... 73.44444444 71.55555556
  72.33333333]
 [64.66666667 63.55555556 63.11111111 ... 74.33333333 72.33333333
  72.55555556]
 [67.11111111 64.55555556 63.33333333 ... 75.22222222 73.33333333
  73.11111111]]


## NIR Band Average

In [12]:
avg_nir = np.zeros((nir.shape[0]-2, nir.shape[1]-2))

#slide a 3x3 window over the near-infrared bands
for i in range(nir.shape[0]-2):
  for j in range(nir.shape[1]-2):
    number_nir= np.average([nir[i][j],nir[i][j+1],nir[i][j+2],
                        nir[i+1][j],nir[i+1][j+1],nir[i+1][j+2],
                        nir[i+2][j],nir[i+2][j+1],nir[i+2][j+2]])
    avg_nir[i][j]=number_nir

In [13]:
print(avg_nir)

[[ 16.88888889  18.55555556  19.22222222 ... 159.55555556 162.11111111
  165.11111111]
 [ 15.88888889  17.33333333  17.77777778 ... 158.22222222 160.88888889
  164.55555556]
 [ 16.55555556  17.11111111  17.11111111 ... 151.88888889 154.33333333
  157.55555556]
 ...
 [ 32.44444444  31.11111111  28.33333333 ... 166.77777778 144.11111111
  130.66666667]
 [ 31.88888889  29.44444444  26.66666667 ... 167.44444444 145.11111111
  127.11111111]
 [ 46.22222222  35.33333333  26.33333333 ... 166.22222222 150.33333333
  137.        ]]


## NDVI Average

In [21]:
np.seterr(divide='ignore', invalid='ignore')
ndvi = (nir-red) / (nir+red)

avg_ndvi = np.zeros((nir.shape[0]-2, nir.shape[1]-2))

#slide a 3x3 window over ndvi value for all pixels
for i in range(nir.shape[0]-2):
  for j in range(nir.shape[1]-2):
    number_ndvi= np.average([ndvi[i][j],ndvi[i][j+1],ndvi[i][j+2],
                        ndvi[i+1][j],ndvi[i+1][j+1],ndvi[i+1][j+2],
                        ndvi[i+2][j],ndvi[i+2][j+1],ndvi[i+2][j+2]])
    avg_ndvi[i][j]=number_ndvi

In [22]:
print(avg_ndvi)

[[3.08242687 2.93775198 2.87334643 ... 0.44768309 0.45084973 0.45830242]
 [3.18048654 3.09537381 3.02910777 ... 0.44134467 0.45179489 0.46441721]
 [3.15841037 3.14790895 3.12599957 ... 0.4394395  0.45324781 0.46483133]
 ...
 [3.35101531 3.40573522 3.67883406 ... 6.25668527 4.05610996 0.31422207]
 [3.44901613 3.59596548 3.85734207 ... 4.9693741  4.05177915 0.30806074]
 [2.71266085 3.18410529 3.76093813 ... 4.5109251  4.05366099 0.32501024]]


## Convert to DataFrame

In [14]:
import pandas as pd

red_df = pd.DataFrame(avg)
red_df.to_csv("red_band_average.csv")

green_df = pd.DataFrame(avg_green)
green_df.to_csv("green_band_average.csv")

blue_df = pd.DataFrame(avg_blue)
blue_df.to_csv("blue_band_average.csv")

nir_df = pd.DataFrame(avg_nir)
nir_df.to_csv("nir_band_average.csv")

In [24]:
ndvi_df = pd.DataFrame(avg_ndvi)
ndvi_df.to_csv("ndvi_average.csv")

In [15]:
red_df

0          1          2          3          4          5      \
0      54.444444  56.222222  57.000000  56.222222  55.777778  58.111111   
1      53.111111  53.777778  54.666667  53.333333  53.777778  54.777778   
2      53.111111  53.000000  53.333333  51.888889  53.111111  53.777778   
3      53.555556  53.000000  52.555556  51.222222  52.444444  53.333333   
4      53.333333  52.444444  51.555556  50.222222  51.111111  51.888889   
...          ...        ...        ...        ...        ...        ...   
12313  42.444444  41.666667  40.444444  39.888889  42.888889  45.222222   
12314  42.555556  42.000000  40.111111  38.222222  41.777778  42.777778   
12315  41.444444  41.444444  39.444444  37.000000  39.111111  39.444444   
12316  40.111111  39.555556  37.777778  35.444444  36.444444  36.666667   
12317  44.111111  41.333333  39.555556  37.222222  37.000000  36.111111   

           6          7           8          9      ...      10808      10809  \
0      72.666667  95.000000  103.666667  89.111111  ...  90.222222  87.555556   
1      60.000000  68.888889   70.777778  66.666667  ...  96.000000  89.333333   
2      55.444444  56.222222   56.777778  57.222222  ...  97.222222  85.777778   
3      55.222222  56.333333   57.333333  58.333333  ...  95.000000  80.111111   
4      53.888889  55.888889   57.666667  58.888889  ...  76.444444  65.000000   
...          ...        ...         ...        ...  ...        ...        ...   
12313  46.777778  46.666667   47.000000  46.222222  ...  80.666667  85.666667   
12314  43.222222  40.666667   41.777778  41.777778  ...  80.333333  83.222222   
12315  40.222222  39.111111   43.333333  45.888889  ...  79.333333  80.333333   
12316  38.111111  40.333333   50.333333  55.444444  ...  80.000000  77.444444   
12317  38.444444  43.444444   60.111111  67.777778  ...  83.888889  78.777778   

           10810      10811      10812      10813      10814      10815  \
0      80.444444  74.777778  67.444444  63.333333  61.777778  60.888889   
1      78.555556  70.888889  64.666667  63.111111  63.000000  61.444444   
2      74.555556  66.000000  61.777778  60.444444  60.555556  59.333333   
3      65.888889  57.333333  54.666667  54.555556  54.444444  54.000000   
4      54.555556  48.666667  47.777778  50.111111  50.888889  50.555556   
...          ...        ...        ...        ...        ...        ...   
12313  85.333333  80.666667  78.000000  77.333333  73.111111  67.444444   
12314  82.333333  78.000000  78.000000  81.222222  78.000000  70.777778   
12315  80.333333  76.444444  76.444444  80.777778  80.444444  73.555556   
12316  75.666667  72.111111  72.333333  77.555556  80.333333  75.777778   
12317  74.111111  70.444444  70.444444  74.777778  78.888889  77.000000   

           10816      10817  
0      61.333333  61.333333  
1      60.777778  60.222222  
2      58.111111  57.555556  
3      52.777778  52.555556  
4      47.000000  45.777778  
...          ...        ...  
12313  63.222222  65.111111  
12314  65.777778  68.000000  
12315  67.111111  67.666667  
12316  68.333333  66.777778  
12317  70.888889  69.111111  

[12318 rows x 10818 columns]

In [16]:
red_df.describe()

0             1             2             3             4      \
count  12318.000000  12318.000000  12318.000000  12318.000000  12318.000000   
mean      97.501073     97.421497     97.282216     97.210694     97.191436   
std       50.334654     50.271230     50.179998     50.007541     49.805345   
min       29.333333     29.222222     29.555556     29.333333     28.888889   
25%       55.666667     55.694444     55.444444     55.444444     55.444444   
50%       81.666667     81.555556     81.333333     81.611111     81.555556   
75%      134.305556    134.111111    134.333333    134.333333    134.305556   
max      228.555556    227.444444    224.000000    222.000000    222.222222   

              5             6             7             8             9      \
count  12318.000000  12318.000000  12318.000000  12318.000000  12318.000000   
mean      97.226209     97.216539     97.115666     97.067435     96.958696   
std       49.590222     49.388239     49.200003     49.043320     48.969826   
min       28.888889     30.000000     29.777778     30.111111     29.333333   
25%       55.555556     55.888889     55.777778     55.805556     55.555556   
50%       82.111111     82.222222     82.444444     83.000000     83.222222   
75%      134.222222    134.000000    133.777778    132.861111    132.555556   
max      222.666667    222.666667    222.333333    221.888889    221.444444   

       ...         10808         10809         10810         10811  \
count  ...  12318.000000  12318.000000  12318.000000  12318.000000   
mean   ...     88.528603     88.316078     88.069095     87.669418   
std    ...     39.931450     39.918177     39.768547     39.540503   
min    ...     32.888889     33.222222     32.777778     31.555556   
25%    ...     57.777778     57.444444     57.555556     57.333333   
50%    ...     77.777778     77.666667     77.555556     77.555556   
75%    ...    110.444444    110.194444    109.777778    108.666667   
max    ...    212.222222    212.000000    211.666667    211.555556   

              10812         10813         10814         10815         10816  \
count  12318.000000  12318.000000  12318.000000  12318.000000  12318.000000   
mean      87.304820     87.145190     87.174938     87.268938     87.396818   
std       39.352168     39.305073     39.313764     39.433077     39.515255   
min       31.222222     31.000000     31.222222     30.333333     30.888889   
25%       57.333333     57.222222     57.444444     57.444444     57.333333   
50%       76.888889     76.666667     76.222222     76.222222     76.555556   
75%      108.555556    108.222222    109.000000    109.555556    109.444444   
max      212.111111    213.000000    213.777778    213.888889    213.888889   

              10817  
count  12318.000000  
mean      87.605473  
std       39.685711  
min       32.444444  
25%       57.444444  
50%       76.555556  
75%      109.111111  
max      213.666667  

[8 rows x 10818 columns]

In [17]:
green_df.describe()

0             1             2             3             4      \
count  12318.000000  12318.000000  12318.000000  12318.000000  12318.000000   
mean     101.938933    101.844897    101.677933    101.518031    101.442704   
std       45.355038     45.307483     45.219950     45.008484     44.776970   
min       36.111111     36.000000     36.000000     35.888889     35.000000   
25%       65.777778     65.333333     65.222222     65.666667     65.555556   
50%       89.666667     89.500000     89.111111     89.000000     89.111111   
75%      132.111111    131.861111    132.111111    131.888889    131.888889   
max      225.666667    225.555556    222.222222    220.444444    220.666667   

              5             6             7             8             9      \
count  12318.000000  12318.000000  12318.000000  12318.000000  12318.000000   
mean     101.431627    101.427090    101.346882    101.275099    101.157674   
std       44.538898     44.355067     44.188517     44.080970     44.036682   
min       35.111111     35.555556     36.333333     36.111111     35.777778   
25%       65.777778     65.888889     65.777778     65.666667     65.444444   
50%       89.000000     89.000000     89.555556     90.111111     90.111111   
75%      131.444444    131.666667    131.666667    131.111111    130.861111   
max      221.111111    221.333333    220.777778    219.888889    219.555556   

       ...         10808         10809         10810         10811  \
count  ...  12318.000000  12318.000000  12318.000000  12318.000000   
mean   ...     94.520846     94.366167     94.169634     93.829644   
std    ...     35.241020     35.292490     35.181578     34.947090   
min    ...     39.666667     39.666667     39.333333     39.555556   
25%    ...     69.000000     68.444444     68.666667     68.444444   
50%    ...     87.111111     87.000000     86.888889     86.777778   
75%    ...    110.555556    110.444444    110.222222    109.666667   
max    ...    213.777778    212.111111    211.888889    211.666667   

              10812         10813         10814         10815         10816  \
count  12318.000000  12318.000000  12318.000000  12318.000000  12318.000000   
mean      93.512204     93.401508     93.448846     93.522839     93.625841   
std       34.766528     34.751286     34.772423     34.867618     34.951327   
min       39.222222     38.444444     39.111111     39.333333     39.222222   
25%       68.222222     67.888889     68.222222     68.361111     68.111111   
50%       86.333333     86.333333     86.000000     86.000000     86.222222   
75%      109.666667    109.777778    110.000000    110.222222    110.000000   
max      212.111111    212.888889    213.888889    214.222222    214.444444   

              10817  
count  12318.000000  
mean      93.796260  
std       35.148604  
min       39.111111  
25%       68.444444  
50%       86.444444  
75%      110.000000  
max      214.222222  

[8 rows x 10818 columns]

In [18]:
blue_df.describe()

0             1             2             3             4      \
count  12318.000000  12318.000000  12318.000000  12318.000000  12318.000000   
mean      98.121926     98.065424     97.954944     97.838042     97.759566   
std       39.333888     39.262920     39.150962     38.949958     38.726548   
min       52.666667     52.777778     52.777778     52.333333     52.555556   
25%       67.222222     67.222222     67.111111     67.222222     67.111111   
50%       82.666667     82.222222     82.222222     82.111111     82.444444   
75%      120.666667    120.555556    120.666667    120.972222    121.222222   
max      223.888889    223.111111    218.555556    215.888889    216.444444   

              5             6             7             8             9      \
count  12318.000000  12318.000000  12318.000000  12318.000000  12318.000000   
mean      97.700934     97.613240     97.515343     97.469927     97.438852   
std       38.482587     38.268398     38.073313     37.932183     37.892378   
min       52.666667     52.888889     53.333333     53.000000     52.555556   
25%       67.222222     67.333333     67.222222     67.000000     67.000000   
50%       82.611111     83.111111     83.444444     83.777778     83.666667   
75%      121.111111    120.888889    120.777778    120.222222    119.750000   
max      217.000000    216.888889    215.777778    215.000000    214.666667   

       ...         10808         10809         10810         10811  \
count  ...  12318.000000  12318.000000  12318.000000  12318.000000   
mean   ...     88.783208     88.686971     88.525013     88.257419   
std    ...     29.194143     29.142710     28.966221     28.749100   
min    ...     56.111111     55.777778     55.333333     54.666667   
25%    ...     68.000000     68.111111     68.111111     68.111111   
50%    ...     79.222222     79.111111     78.777778     78.555556   
75%    ...     97.333333     97.222222     97.111111     97.000000   
max    ...    211.000000    206.222222    205.555556    205.333333   

              10812         10813         10814         10815         10816  \
count  12318.000000  12318.000000  12318.000000  12318.000000  12318.000000   
mean      88.026285     87.978577     88.051776     88.138199     88.248155   
std       28.638602     28.717562     28.853565     29.001798     29.112024   
min       54.333333     54.111111     54.555556     54.777778     55.222222   
25%       68.222222     68.000000     68.000000     67.888889     68.000000   
50%       78.000000     77.666667     77.444444     77.444444     77.666667   
75%       97.000000     97.444444     97.555556     97.888889     97.666667   
max      206.111111    207.222222    208.666667    208.888889    208.888889   

              10817  
count  12318.000000  
mean      88.415426  
std       29.280483  
min       56.111111  
25%       68.111111  
50%       77.888889  
75%       97.777778  
max      208.444444  

[8 rows x 10818 columns]

In [19]:
nir_df.describe()

0             1             2             3             4      \
count  12318.000000  12318.000000  12318.000000  12318.000000  12318.000000   
mean     121.394463    121.280763    121.187792    121.077033    121.043721   
std       53.179338     53.035987     52.746426     52.341973     51.925528   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%       83.777778     83.777778     85.583333     85.777778     85.777778   
50%      131.666667    132.000000    131.222222    130.888889    130.555556   
75%      164.111111    163.444444    163.305556    163.222222    163.000000   
max      229.333333    228.444444    224.444444    219.222222    221.222222   

              5             6             7             8             9      \
count  12318.000000  12318.000000  12318.000000  12318.000000  12318.000000   
mean     121.172079    121.289955    121.135781    120.837898    120.473426   
std       51.656553     51.617186     51.783224     51.929838     51.945396   
min        1.000000      1.000000      1.000000      1.000000      1.000000   
25%       86.888889     87.222222     86.000000     84.666667     83.555556   
50%      131.444444    132.000000    131.333333    130.944444    130.444444   
75%      162.555556    162.555556    162.444444    162.555556    162.111111   
max      222.666667    223.111111    222.333333    221.000000    219.333333   

       ...         10808         10809         10810         10811  \
count  ...  12318.000000  12318.000000  12318.000000  12318.000000   
mean   ...    121.529668    121.336066    121.096688    120.751754   
std    ...     45.510179     45.854531     46.085188     46.129169   
min    ...      8.888889      8.666667      9.000000      8.777778   
25%    ...     85.888889     85.000000     85.000000     84.111111   
50%    ...    134.333333    134.555556    134.444444    134.000000   
75%    ...    158.666667    158.777778    159.222222    159.111111   
max    ...    203.111111    202.888889    202.777778    202.777778   

              10812         10813         10814         10815         10816  \
count  12318.000000  12318.000000  12318.000000  12318.000000  12318.000000   
mean     120.486190    120.434143    120.634997    120.740425    120.739848   
std       45.971947     45.648143     45.178509     44.753829     44.445142   
min        7.333333      6.888889      6.888889      6.333333      6.000000   
25%       84.111111     85.000000     85.888889     86.805556     87.444444   
50%      132.777778    132.555556    133.000000    133.111111    132.555556   
75%      158.888889    157.777778    157.111111    156.666667    156.555556   
max      203.333333    204.111111    205.000000    205.222222    205.444444   

              10817  
count  12318.000000  
mean     120.572550  
std       44.420154  
min        5.555556  
25%       87.333333  
50%      132.333333  
75%      156.000000  
max      205.444444  

[8 rows x 10818 columns]

In [25]:
ndvi_df.describe()

0             1             2             3             4      \
count  1.231500e+04  1.231200e+04  1.231200e+04  1.231500e+04  1.231800e+04   
mean            inf           inf           inf           inf           inf   
std             NaN           NaN           NaN           NaN           NaN   
min    1.610583e-02  9.843789e-03  8.057321e-03  1.049095e-02  7.882988e-03   
25%    4.943117e-01  4.894745e-01  4.843613e-01  4.763011e-01  4.777335e-01   
50%    1.679165e+00  1.650536e+00  1.612523e+00  1.596778e+00  1.612180e+00   
75%    3.642498e+00  3.645411e+00  3.631010e+00  3.648671e+00  3.680318e+00   
max             inf           inf           inf           inf           inf   

              5             6             7             8             9      \
count  1.231800e+04  1.231800e+04  1.231800e+04  1.231800e+04  1.231800e+04   
mean            inf           inf           inf           inf           inf   
std             NaN           NaN           NaN           NaN           NaN   
min    1.374181e-02  1.252735e-02  1.484261e-02  1.458039e-02  1.478147e-02   
25%    4.754842e-01  4.753880e-01  4.724544e-01  4.740819e-01  4.842604e-01   
50%    1.623044e+00  1.641615e+00  1.628565e+00  1.626318e+00  1.636488e+00   
75%    3.727634e+00  3.757169e+00  3.743018e+00  3.740008e+00  3.731565e+00   
max             inf           inf           inf           inf           inf   

       ...         10808         10809         10810         10811  \
count  ...  1.231800e+04  1.231800e+04  1.231800e+04  1.231800e+04   
mean   ...           inf           inf           inf           inf   
std    ...           NaN           NaN           NaN           NaN   
min    ...  2.477089e-02  2.576322e-02  3.049688e-02  3.872856e-02   
25%    ...  4.031850e-01  4.058745e-01  4.055014e-01  4.056397e-01   
50%    ...  1.412846e+00  1.455466e+00  1.466558e+00  1.448989e+00   
75%    ...  3.357096e+00  3.451354e+00  3.444312e+00  3.446322e+00   
max    ...           inf           inf           inf           inf   

              10812         10813         10814         10815         10816  \
count  1.231800e+04  1.231800e+04  1.231800e+04  1.231500e+04  1.231500e+04   
mean            inf           inf           inf           inf           inf   
std             NaN           NaN           NaN           NaN           NaN   
min    2.434631e-02  2.650734e-02  3.036321e-02  2.045764e-02  2.559100e-02   
25%    4.065936e-01  4.027302e-01  4.038404e-01  4.006972e-01  3.924819e-01   
50%    1.421241e+00  1.394151e+00  1.386429e+00  1.373978e+00  1.337993e+00   
75%    3.434225e+00  3.422236e+00  3.424625e+00  3.411935e+00  3.356054e+00   
max             inf           inf           inf           inf           inf   

              10817  
count  1.231500e+04  
mean            inf  
std             NaN  
min    4.114333e-02  
25%    3.879830e-01  
50%    1.368496e+00  
75%    3.341826e+00  
max             inf  

[8 rows x 10818 columns]

### Discovery

If we cut the image using vertical stripes, and using the "describe" table above, we can find that:

1. The minimum of nir value equals 1 in the first few columns. And a nir value equals 1 means the surface in the image is water. Therefore, we can tell there should be a river/water crossing from left part of the image.